requirejs.config({
  baseUrl: 'src',
  paths: {
    //---------------------------------------------------
    // vanilla libraries
    //---------------------------------------------------
    'angular':               '../bower_components/angular/angular.min',
    'angular-bootstrap':     '../bower_components/angular-bootstrap/ui-bootstrap-tpls',
    'angular-highlightjs':   '../bower_components/angular-highlightjs/angular-highlightjs.min',
    'angular-knife':         '../bower_components/angular-knife/build/angular-knife-min',
    'angular-route':         '../bower_components/angular-route/angular-route.min',
    'angular-ui-router':     '../bower_components/angular-ui-router/release/angular-ui-router.min',
    'angular-ui-slider':     '../bower_components/angular-ui-slider/src/slider',
    'angular-ui-sortable':   '../bower_components/angular-ui-sortable/sortable.min',
    'angular-spinkit':       '../bower_components/angular-spinkit/build/angular-spinkit.min',
    'angular-sanitize':      '../bower_components/angular-sanitize/angular-sanitize.min',
    'angular-sstooltip':     '../bower_components/sstooltip/dist/angular-sstooltip.min',
    'bootstrap':             '../bower_components/bootstrap/dist/js/bootstrap',
    'cola':                  '../bower_components/webcola/WebCola/cola.v1.min',
    'd3':                    '../bower_components/d3/d3.min',
    'd3.promise':            '../bower_components/d3.promise/src/d3.promise',
    'domReady':              '../bower_components/requirejs-domready/domReady',
    'highlightjs':           '../bower_components/highlightjs/highlight.pack',
    'html2canvas':           '../bower_components/html2canvas/build/html2canvas.min',
    'jquery':                '../bower_components/jquery/dist/jquery.min',
    'jquery-ui':             '../bower_components/jquery-ui/ui/minified/jquery-ui.min',
    'lodash':                '../bower_components/lodash/dist/lodash.min',
    'lunr':                  '../bower_components/lunr.js/lunr.min',
    'moment':                '../bower_components/momentjs/min/moment.min',
    'ng-debounce':           '../bower_components/ng-debounce/angular-debounce',
    'ng-table':              '../bower_components/ng-table/ng-table.min',
    'ng-vega':               '../bower_components/ng-vega/src/ng-vega',
    'queue':                 '../bower_components/queue-async/queue.min',
    'rickshaw':              '../bower_components/rickshaw/rickshaw.min',
    'sstooltip':             '../bower_components/sstooltip/dist/sstooltip.min',
    'topojson':              '../bower_components/topojson/topojson',
    'underscore.string':     '../bower_components/underscore.string/dist/underscore.string.min',
    'colorbrewer':           '../bower_components/colorbrewer/colorbrewer',
    'vega':                  '../vendor/vega/vega-umd',
  },
  shim: {
    'angular':                {exports: 'angular'},
    'angular-bootstrap':      {deps: ['angular', 'bootstrap']},
    'angular-highlightjs':    {deps: ['angular', 'pure/js/shim/highlightjsShim']},
    'angular-knife':          {deps: ['angular']},
    'angular-route':          {deps: ['angular']},
    'angular-ui-router':      {deps: ['angular']},
    'angular-ui-slider':      {deps: ['angular', 'jquery-ui']},
    'angular-ui-sortable':    {deps: ['angular', 'jquery-ui']},
    'angular-spinkit':        {deps: ['angular']},
    'angular-sanitize':       {deps: ['angular']},
    'bootstrap':              {deps: ['jquery']},
    'cola':                   {exports: 'cola', deps: ['d3', 'pure/js/shim/d3Shim']},
    'colorbrewer':            {exports: 'colorbrewer'},
    'jquery-ui':              {deps: ['jquery']},
    'highlightjs':            {exports: 'hljs'},
    'html2canvas':            {exports: 'html2canvas'},
    'lunr':                   {exports: 'lunr'},
    'ng-debounce':            {deps: ['angular']},
    'ng-table':               {deps: ['angular']}
  }
});
